name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  hooks_riverpod: ^2.5.1
  logger: ^2.2.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  pedantic_mono: any

flutter:

  uses-material-design: true
