name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  roggle: ^0.4.2+1
  shared_preferences: ^2.2.3
  turn_page_transition: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  pedantic_mono: any

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
    - family: ShipporiMincho
      fonts:
        - asset: assets/fonts/Shippori_Mincho/ShipporiMincho-Regular.ttf
          weight: 400
        - asset: assets/fonts/Shippori_Mincho/ShipporiMincho-Medium.ttf
          weight: 500
        - asset: assets/fonts/Shippori_Mincho/ShipporiMincho-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Shippori_Mincho/ShipporiMincho-Bold.ttf
          weight: 700
        - asset: assets/fonts/Shippori_Mincho/ShipporiMincho-ExtraBold.ttf
          weight: 800

flutter_icons:
  ios: true
  image_path: "assets/images/launcher/icon_ios.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/images/launcher/icon_adaptive_background.png"
  adaptive_icon_foreground: "assets/images/launcher/icon_adaptive_foreground.png"
