name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  hooks_riverpod: ^2.4.0
  logger: ^2.0.2

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  pedantic_mono: any

flutter:

  uses-material-design: true
