import 'package:flutter/material.dart';

class AppColorSchemes {
  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff765a0b),
    surfaceTint: Color(0xff765a0b),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffffdf99),
    onPrimaryContainer: Color(0xff251a00),
    secondary: Color(0xff6a5d3f),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xfff4e0bb),
    onSecondaryContainer: Color(0xff241a04),
    tertiary: Color(0xff496548),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffcbebc6),
    onTertiaryContainer: Color(0xff062109),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    surface: Color(0xfffff8f2),
    onSurface: Color(0xff1f1b13),
    onSurfaceVariant: Color(0xff4d4639),
    outline: Color(0xff7e7667),
    outlineVariant: Color(0xffd0c5b4),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff353027),
    inversePrimary: Color(0xffe7c26c),
    primaryFixed: Color(0xffffdf99),
    onPrimaryFixed: Color(0xff251a00),
    primaryFixedDim: Color(0xffe7c26c),
    onPrimaryFixedVariant: Color(0xff5a4300),
    secondaryFixed: Color(0xfff4e0bb),
    onSecondaryFixed: Color(0xff241a04),
    secondaryFixedDim: Color(0xffd7c5a0),
    onSecondaryFixedVariant: Color(0xff52452a),
    tertiaryFixed: Color(0xffcbebc6),
    onTertiaryFixed: Color(0xff062109),
    tertiaryFixedDim: Color(0xffafcfab),
    onTertiaryFixedVariant: Color(0xff324d32),
    surfaceDim: Color(0xffe2d9cc),
    surfaceBright: Color(0xfffff8f2),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfffcf2e5),
    surfaceContainer: Color(0xfff6eddf),
    surfaceContainerHigh: Color(0xfff0e7d9),
    surfaceContainerHighest: Color(0xffebe1d4),
  );
}
